In [ ]:
# Employee Records

# Display employees whose salary is greater than 50,000.
# Display only employees from the IT department.

In [7]:
import pandas as pd

df = pd.DataFrame({
    "Employee": ["John", "Sarah", "Mike", "Emma", "Alex"],
    "Salary": [40000, 65000, 55000, 72000, 38000],
    "Department": ["HR", "IT", "Sales", "IT", "HR"]
})

print(df)

  Employee  Salary Department
0     John   40000         HR
1    Sarah   65000         IT
2     Mike   55000      Sales
3     Emma   72000         IT
4     Alex   38000         HR

In [8]:
df[df["Salary"] > 50000]

  Employee  Salary Department
1    Sarah   65000         IT
2     Mike   55000      Sales
3     Emma   72000         IT

In [9]:
df[df["Department"] == "IT"]

  Employee  Salary Department
1    Sarah   65000         IT
3     Emma   72000         IT