In [1]:
# Customer Database

# Remove duplicate rows.
# Sort the DataFrame by Purchase in descending order.

In [4]:
import pandas as pd

df = pd.DataFrame({
    "Name": ["Alice", "Bob", "Alice", "David", "Bob", "Eva"],
    "City": ["Delhi", "Mumbai", "Delhi", "Pune", "Mumbai", "Chennai"],
    "Purchase": [500, 800, 500, 1200, 800, 650]
})

print(df)

    Name     City  Purchase
0  Alice    Delhi       500
1    Bob   Mumbai       800
2  Alice    Delhi       500
3  David     Pune      1200
4    Bob   Mumbai       800
5    Eva  Chennai       650

In [3]:
df.drop_duplicates()

    Name     City  Purchase
0  Alice    Delhi       500
1    Bob   Mumbai       800
3  David     Pune      1200
5    Eva  Chennai       650

In [7]:
df.sort_values(by = "Purchase" , ascending = True)

    Name     City  Purchase
0  Alice    Delhi       500
2  Alice    Delhi       500
5    Eva  Chennai       650
1    Bob   Mumbai       800
4    Bob   Mumbai       800
3  David     Pune      1200