In [ ]:
# Exam Results

# Display the second and fourth rows using iloc.
# Display only the Math and Science columns.

In [9]:
import pandas as pd

df = pd.DataFrame({
    "Student": ["A", "B", "C", "D", "E"],
    "Math": [80, 92, 68, 95, 77],
    "Science": [75, 88, 72, 91, 79],
    "English": [82, 90, 70, 94, 81]
})

print(df)

  Student  Math  Science  English
0       A    80       75       82
1       B    92       88       90
2       C    68       72       70
3       D    95       91       94
4       E    77       79       81

In [8]:
df.iloc[[1,3]]

  Student  Math  Science  English
1       B    92       88       90
3       D    95       91       94

In [15]:
df[["Math","Science"]]

   Math  Science
0    80       75
1    92       88
2    68       72
3    95       91
4    77       79