In [ ]:
# Student Information 

# Display the first 3 rows.
# Display only the Name and City columns.

In [4]:
import pandas as pd

df = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie", "David", "Eva"],
    "Age": [20, 22, 19, 21, 23],
    "City": ["Delhi", "Mumbai", "Pune", "Chennai", "Bangalore"]
})

print(df)

      Name  Age       City
0    Alice   20      Delhi
1      Bob   22     Mumbai
2  Charlie   19       Pune
3    David   21    Chennai
4      Eva   23  Bangalore

In [5]:
df.head(3)

      Name  Age    City
0    Alice   20   Delhi
1      Bob   22  Mumbai
2  Charlie   19    Pune

In [6]:
df[["Name","City"]]

      Name       City
0    Alice      Delhi
1      Bob     Mumbai
2  Charlie       Pune
3    David    Chennai
4      Eva  Bangalore